---
kubernetes:
  children:
    master:
      hosts:
        k8s-master01:
        k8s-master02:
        k8s-master03:
    worker:
      hosts:
        k8s-worker01:
        k8s-worker02:
        k8s-worker03:
        k8s-worker04:
