# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:YZ+ffOLv5pzj3dGIow==,iv:qkk8KkjMVgh7CJWCQyY6ac8wnMT9LTiXmFWRUPDfczM=,tag:PpsYoQBeIpQ07DQSLe6NCg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ZbV42XzcaLlWaPjTC8FRtchQqb0=,iv:G03eeGzFhT2Q/5aUD/3/RpZ+3n2Eddsh7snAEUrUd6o=,tag:aHwsB/j0An+VF2XXLhjhig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q5fzt664n3mp0e2u35m5whp3gykzdc5m068540fx6cz47gpxrchsq6glq6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSmVIQnp1MFZTNUdmb25v
            bzQ1b0JNWU9WNHh6dXRFbjFqQVI4bCtQRUZNCjRhbnVKUXA4d2loK25JS1hQMDg5
            YjlDMUlkZHUwNU9Sa3g5b3FyOEdmNVEKLS0tIFJVOHd3Qm1RZm5sZ2hmaWVLeXFU
            SnJrRDE1UERESmUyMGdZVmplV1VQM28Kh2Sk5cU7Ys/dzJzUg7awroYmkok2R/8z
            8KrCmx+CWYEaH5Vs6a0mLwIrDhpyAWnu0GRjn5XLWDYZDY75fPxEAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-22T13:40:49Z"
    mac: ENC[AES256_GCM,data:gGqdFXubn3LkYh6h7XFEhp8qlKialSdosuWioPD7vXI4/oNcTPI/4izdnh5Ytv9JKe8coBvZfzVZMhOG2400G2UHOY4se41K02Np7325vX2Ne/fabjjls0wxbcNUXtFwgSZOxiG/Ydg5nc227ZQd1QB02wUuDE7DDhpFqUvuBeQ=,iv:Y2WrAy3RT8wRInD5oNbzyuXXwNP9+m45J8zz00FSleA=,tag:kpRWaqUG17wrX5EX1nv5/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
